/*DROP TABLE USER_TABLE CASCADE CONSTRAINTS;
DROP TABLE EVENT_TYPE CASCADE CONSTRAINTS;
DROP TABLE GRADING_FORMATS CASCADE CONSTRAINTS;
DROP TABLE GRADE_TABLE CASCADE CONSTRAINTS;
DROP TABLE PRESENTATION CASCADE CONSTRAINTS;
DROP TABLE FORMS CASCADE CONSTRAINTS;*/


CREATE TABLE USER_TABLE(
    USERID NUMBER,
    FIRSTNAME VARCHAR2(25) NOT NULL,
    LASTNAME VARCHAR2(25) NOT NULL,
    EMAIL VARCHAR2(50),
    DEPARTMENT VARCHAR2(20) NOT NULL,
    POSITION VARCHAR2(30) NOT NULL,
    SUPERVISOR NUMBER,
    CONSTRAINT PK_USERID PRIMARY KEY (USERID),
    CONSTRAINT FK_SUPERVISOR FOREIGN KEY (SUPERVISOR) REFERENCES USERTABLE);

CREATE TABLE EVENT_TYPE(
    EVENT_ID NUMBER,
    EVENT_NAME VARCHAR2(40),
    R_PERCENTAGE NUMBER,
    CONSTRAINT PK_EVENT_ID PRIMARY KEY (EVENT_ID));
    
CREATE TABLE GRADING_FORMATS(
    GRADE_FORMATID NUMBER,
    GRADE_FORMAT VARCHAR2(20),
    CONSTRAINT PK_GRADE_FORMATID PRIMARY KEY(GRADE_FORMATID));
    
CREATE TABLE GRADE_TABLE(
    GRADEID NUMBER,
    USERID NUMBER,
    GRADE VARCHAR2(10),
    GRADE_FORMATID NUMBER,
    CONSTRAINT PK_GRADEID PRIMARY KEY (GRADEID),
    CONSTRAINT FK_G_USERID FOREIGN KEY (USERID) REFERENCES USERTABLE,
    CONSTRAINT FK_GRADE_FORMATID FOREIGN KEY (GRADE_FORMATID) REFERENCES GRADING_FORMATS (GRADE_FORMATID));

CREATE TABLE PRESENTATION(
    PRESENTATIONID NUMBER,
    DESCRIPTION VARCHAR2(255),
    USERID NUMBER,
    SATIFACTORY CHAR(1),
    CONSTRAINT PK_PRESENTATIONID PRIMARY KEY (PRESENTATIONID),
    CONSTRAINT FK_USERID FOREIGN KEY (USERID) REFERENCES USERTABLE (USERID));
    
CREATE TABLE FORMS(
    FORMID NUMBER,
    USERID NUMBER NOT NULL,
    EDATE DATE,
    ETIME TIMESTAMP,
    ELOCATION VARCHAR2(50),
    DESCRIPTION VARCHAR2(255),
    COST NUMBER,
    GRADING_FORMAT NUMBER,
    EVENT_TYPEID NUMBER,
    JUSTIFICATION VARCHAR2(255),
    CONSTRAINT PK_FORMID PRIMARY KEY (FORMID),
    CONSTRAINT FK_EVENTID FOREIGN KEY (EVENT_TYPEID) REFERENCES EVENTTYPE (EVENTID),
    CONSTRAINT FK_GRADING_FORMAT FOREIGN KEY (GRADING_FORMAT) REFERENCES GRADING_FORMATS (GRADE_FORMATID));
    
CREATE TABLE LOGIN_INFORMATION (
    USERID NUMBER NOT NULL,
    USERNAME VARCHAR2(20) NOT NULL,
    PASSWORD VARCHAR2(20) NOT NULL, 
    CONSTRAINT LOGIN_INFORMATION_FK1 FOREIGN KEY (USERID) REFERENCES USER_TABLE(USERID));